"""创建suno job表

Revision ID: 1d2fa29e9257
Revises: 
Create Date: 2024-09-23 10:49:33.580383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d2fa29e9257'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suno_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(length=10), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('request', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suno_jobs_id'), 'suno_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_suno_jobs_job_id'), 'suno_jobs', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suno_jobs_job_id'), table_name='suno_jobs')
    op.drop_index(op.f('ix_suno_jobs_id'), table_name='suno_jobs')
    op.drop_table('suno_jobs')
    # ### end Alembic commands ###
