services:
  sunoapi:
    build: 
      context: ../
      dockerfile: Dockerfile
    image: sunoapi:5.22.3_fix1
    # image: registry.cn-shanghai.aliyuncs.com/miaocode/sunoapi:5.22.3_fix1

    command: tail -f /dev/null
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./volumes/logs:/app/storage/logs
      - ./.env:/app/.env
    ports:
      - ${SUNO_PORT:-8000}:8000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - gt_network
networks:
  gt_network:
    name: gt_network
    driver: bridge