services:
  sunoapi:
    build: 
      context: ../
      dockerfile: Dockerfile
    image: sunoapi:5.20.0
    command: tail -f /dev/null
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./volumes/logs:/app/storage/logs
      - ./.env:/app/.env
    ports:
      - ${SUNO_PORT:-8000}:8000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"