"""add suno job

Revision ID: 3e9333579efd
Revises: 
Create Date: 2024-10-09 11:08:33.294829

"""
from alembic import op
import sqlalchemy as sa

import models


# revision identifiers, used by Alembic.
revision = '3e9333579efd'
down_revision = '000000000000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suno_jobs',
    sa.Column('id', models.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('job_id', sa.String(length=40), nullable=True),
    sa.Column('job_type', sa.String(length=10), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('request', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suno_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suno_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suno_jobs_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suno_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suno_jobs_job_id'))
        batch_op.drop_index(batch_op.f('ix_suno_jobs_id'))

    op.drop_table('suno_jobs')
    # ### end Alembic commands ###
